INSERT INTO `mydb`.`Cliente` (`nombre`, `direccion`, `email`) VALUES ( "Pepe", "Cra 99 Av. Occidental", "pepe_mexico@gmail.com");
INSERT INTO `mydb`.`Cliente` (`nombre`, `direccion`, `email`) VALUES ( "Bart", "Av Siempre viva 742 Springfield", "elBarto@gmail.com");
select	* from `Cliente` ;
INSERT INTO `mydb`.`Producto` (`nombre`, `descripcion`, `precio`) VALUES ("casco", "casco marca pepito", 250000);
INSERT INTO `mydb`.`Producto` (`nombre`, `descripcion`, `precio`) VALUES ("chaqueta", "chaqueta reflectiva", 100000);
INSERT INTO `mydb`.`Producto` (`nombre`, `descripcion`, `precio`) VALUES ("guantes", "guantes de cuero", 65000);
select	* from `Producto` ;
#UPDATE Producto SET precio = 65000 WHERE idProducto = 3;
INSERT INTO `mydb`.`Empleado` (`nombre`, `cargo`) VALUES ("Juan", "Vendedor");
select	* from `Empleado` ;
INSERT INTO `mydb`.`Pedido` (`fecha`, `estado`, `idCliente`, `idEmpleado`) VALUES (NOW(), 1, 1, 1);
INSERT INTO `mydb`.`Pedido` (`fecha`, `estado`, `idCliente`, `idEmpleado`) VALUES (NOW(), 1, 2, 1);
select	* from `Pedido` ;
INSERT INTO `mydb`.`pedido_producto` (`idPedido`, `idProducto`, `cantidad`) VALUES (1, 1, 7);
INSERT INTO `mydb`.`pedido_producto` (`idPedido`, `idProducto`, `cantidad`) VALUES (1, 2, 4);
INSERT INTO `mydb`.`pedido_producto` (`idPedido`, `idProducto`, `cantidad`) VALUES (4, 1, 4);
INSERT INTO `mydb`.`pedido_producto` (`idPedido`, `idProducto`, `cantidad`) VALUES (4, 2, 5);
select	* from `pedido_producto` ;
select	* from `pedido_producto` where idPedido = 4;
SELECT idPedido FROM Pedido where idCliente = 1;
select	* from `pedido_producto` where idPedido IN (SELECT idPedido FROM Pedido where idCliente = 1);